### ISSUE TITLE
Multiple file upload gets error

### ISSUE THREAD

**Issue by vishant2211** [MrMartiniMo/loopback-component-storage-gridfs#5]
When i upload multiple file with same file type, i get error like this..

```
/home/vishant/devcenter/api/node_modules/loopback-component-storage-gridfs/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:344:11)
    at ServerResponse.header (/home/vishant/devcenter/api/node_modules/express/lib/response.js:718:10)
    at ServerResponse.send (/home/vishant/devcenter/api/node_modules/express/lib/response.js:163:12)
    at ServerResponse.json (/home/vishant/devcenter/api/node_modules/express/lib/response.js:249:15)
    at Object.sendBodyJson [as sendBody] (/home/vishant/devcenter/api/node_modules/strong-remoting/lib/http-context.js:509:7)
    at HttpContext.done (/home/vishant/devcenter/api/node_modules/strong-remoting/lib/http-context.js:646:24)
    at /home/vishant/devcenter/api/node_modules/strong-remoting/lib/rest-adapter.js:461:11
    at /home/vishant/devcenter/api/node_modules/async/lib/async.js:251:17
    at /home/vishant/devcenter/api/node_modules/async/lib/async.js:154:25
    at /home/vishant/devcenter/api/node_modules/async/lib/async.js:248:21
```

It works fine on simgle file upload

**Comment by MrMartiniMo** [comment]
Hi vishant2211, thank you for your feedback. I was unable to reproduce it, can you please set up an example?

**Comment by vishant2211** [comment]
I am using postman to upload file.. 
So whenever i select multiple files to upload.. it throws some error i mention above.
![screenshot from 2016-05-09 16 00 59](https://cloud.githubusercontent.com/assets/6287264/15110649/dbc8f202-15ff-11e6-8252-605a4a2a2467.png)

Here i have selected 4 image file with same type(jpg).

**Comment by 1968martino** [comment]
Is there a sample project that use the component, because i don't know how to implement it?
